FROM mikenye/youtube-dl:latest

# Install spleeter
RUN pip3 install spleeter

COPY src/ /src

RUN pip3 uninstall -y tensorflow tensorflow-cpu
RUN pip3 install tensorflow-aarch64 -f https://tf.kmtea.eu/whl/stable.html

ENTRYPOINT ["python", "/src/main.py"]